### ISSUE TITLE
Help Needed with Installing Neo4j Concepts Server Plugin for GEPI

### ISSUE THREAD

**Issue by JXZ454646** [JULIELab/gepi#270]
I am currently working with the GePI Gene Concept Database from your GEPI project and have encountered some difficulties. Specifically, I am trying to install the Neo4j Concepts Server Plugin. Although I followed the provided instructions and converted the plugin to a jar file, it doesn't seem to be working as expected.

Could you please provide a detailed installation guide for the Neo4j Concepts Server Plugin? Any additional tips or common pitfalls to avoid would also be greatly appreciated.

Thank you very much for your assistance and for the valuable work you are doing with this project.

**Comment by khituras** [comment]
I will close this for now. Feel free to comment if there are more issues.
