### ISSUE TITLE
paper outline

### ISSUE THREAD

**Issue by SchSascha** [JULIELab/gepi#45]
points to address
- who are our rivals? Where and why are we significantly more awesome?
- how to tell the story? most likely, we should include several query scenarios, ideally showing something with existing data that has not been seen before?
    - verification experiments?
- where to go? Reach and try high: Nature Methods
  - Policy, Requirements, etc.

**Comment by khituras** [comment]
Paper has been published in NAR Web Server issue: https://academic.oup.com/nar/article/51/W1/W237/7177881.
