### ISSUE TITLE
table 2nd sheet most frequent hits sorted 

### ISSUE THREAD

**Issue by SchSascha** [JULIELab/gepi#95]
I want a second sheet in the result table, termed Frequency of Hits (or something shorter and more exciting) that summarizes the event results
2 possibilities
- A search
  - Show the most frequent event targets for A search members (2 columns: Gene Name (PrefererredName), Frequency)
- B search
  - Show for both input vectors the most frequent members of events (4 columns)

Alternatively, also A search could have a 4 column frequency summary, as it might be interesting, which of the input genes were occurring most frequent.
Would have the advantage that there is only one styled frequency result table necessary (4 columns, 2 summarizing left hand side (A side, name and frequency) and 2 summarizing right hand side (B side, name and frequency))

**Comment by khituras** [comment]
The Excel output of GePI contains such sheets. Closing.
